version: '3'

services:
  nginx:
    build: nginx
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
    working_dir: /var/www
    networks:
      - appnet
    volumes:
      - ..:/var/www:ro
      - ./php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d/:/etc/nginx/conf.d/
  php-fpm:
    build: php-fpm
    working_dir: /var/www
    depends_on:
      - db
    networks:
      - appnet
    volumes:
      - ..:/var/www
      - ./php-fpm/local.ini:/etc/php/7.4/cli/php.ini
      - ./php-fpm/local.ini:/usr/local/etc/php/php.ini
  db:
    build: db
    #    command: --default-authentication-plugin=mysql_native_password
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "telebot"
      MYSQL_USER: "default"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - db
    ports:
      - "3306:3306"
    networks:
      - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  db:
    driver: "local"
